local design = {}
design.zones = {}
design.zones.main = {}
design.main = {
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
design.zones.main.input = {2,2,17,11}
design.zones.main.output = {19,2,34,11}
design.zones.main.storage = {2,13,34,22}